### ISSUE TITLE
does not work with version 8 of angular

### ISSUE THREAD

**Issue by justAnormalUser00** [pIvan/ngx-color-picker#1]
its working i am just stupid

**Comment by pIvan** [comment]
Hi @justAnormalUser00,
I didn't had time to test it with new angular version, will do that in next few weeks.
Can you tell me what happened?

**Comment by justAnormalUser00** [comment]
its complaining about @angular/animations/src/animation_metadata in color-presets-sublist.animation.d.ts
i changed `export declare const OpacityAnimation: import("@angular/animations/src/animation_metadata").AnimationTriggerMetadata;` to => `export declare const OpacityAnimation: import("@angular/animations").AnimationTriggerMetadata;`

locally and it works

**Comment by pIvan** [comment]
That should work locally, but once you run npm install, will not.
I will try to update library as soon I can.

**Comment by justAnormalUser00** [comment]
perfect thx

**Comment by pIvan** [comment]
library was [updated](https://github.com/pIvan/ngx-color-picker/commit/f41102b8e0d725f8804a929c65c7ff9babf2c1fe),
**BrowserAnimationModule** is separated from **ColorPickerModule**, please check use [instruction](https://pivan.github.io/ngx-color-picker/#installation).

**Comment by justAnormalUser00** [comment]
works flawlessly, thx for your work!

**Comment by pIvan** [comment]
you're welcome @justAnormalUser00
