### ISSUE TITLE
How can I use the chrome-wrapper with reactive form

### ISSUE THREAD

**Issue by chrislingxiao** [pIvan/ngx-color-picker#14]
I couldn't find an example from your codebase about having it working with the reactive form like:

`<chrome-wrapper formControlName="colour" [(color)]="colour"></chrome-wrapper>`

do you mind providing an example? this really helps. Thank you

**Comment by pIvan** [comment]
Hi @chrislingxiao before a week I have told how chrome-wrapper is
not a part of this a library, it is just an example of how anybody can wrap
each of the library components in something similar.

How you could use it is to add this to annotation
`providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => ChromePickerComponent),
            multi: true
        }
    ],`

and implement interface ControlValueAccessor
`implements ControlValueAccessor`
