### ISSUE TITLE
Color picker doesn't change value for HEX with minor 0

### ISSUE THREAD

**Issue by kuhtini** [pIvan/ngx-color-picker#17]
Hello. Thanx for a good lib.
 
There is an issue with updating color in HEX input. If the input value has minor 0
#0FFDAF
#012234

Conversion on line 55 will remove minor 0 and values are not equal. 

https://github.com/pIvan/ngx-color-picker/blob/698bf18e7087cc056e1a6cd63deb4a44ab793fef/projects/iplab/ngx-color-picker/src/lib/components/parts/inputs/hex-input/hex-input.component.ts#L55
![conversion-example](https://user-images.githubusercontent.com/22331089/83021892-5cdd3a80-a033-11ea-9b81-b9a2f545ff73.png)
Maybe another HEX validation can be applied.
E.g. with regexp ^[0-9a-fA-F]+$
I tried to create a pull request with 2 lines change but failed due to access issues

**Comment by pIvan** [comment]
Hi @kuhtini can you confirm how the issue is resolved?
Thanks, Ivan

**Comment by kuhtini** [comment]
@pIvan Thanks, It works
