### ISSUE TITLE
showPresets() is not working

### ISSUE THREAD

**Issue by ShivamShokeen** [pIvan/ngx-color-picker#24]
```
 chromeControl = new ColorPickerControl().setValueFrom('rgb(38, 40, 138)').hidePresets().hideAlphaChannel();

 showPresents() {
    this.chromeControl = new ColorPickerControl().setValueFrom('rgb(38, 40, 138)').showPresets();
  }
```

I created a function to enable showPresents() but it's not working. It's showing alpha but it's not showing colour boxes.

**Comment by pIvan** [comment]
Hi @ShivamShokeen,

why are you making a new instance of the same object?
This should be ok.

` chromeControl = new ColorPickerControl().setValueFrom('rgb(38, 40, 138)').hidePresets().hideAlphaChannel();

 showPresents() {
    this.chromeControl.showPresets();
  }`

**Comment by ShivamShokeen** [comment]
Thank You. It's working now :).
