### ISSUE TITLE
Support start and end events?

### ISSUE THREAD

**Issue by StringKe** [pIvan/ngx-color-picker#25]
Now there is only the `colorChange` event. I need to save a history record. I need to use the `start` and `end` events. Can these two events be supported?

**Comment by pIvan** [comment]
Hi @StringKe, can you give me an example of how these `start` and `end` events should work? They should be updated on each slider `change`, for each pixel?

**Comment by StringKe** [comment]
Use the pan related events in hammer js in angular.

```angular
<div
        (panstart)="onPanStart($event, button)" // like mouseDown
        (panmove)="onPanMove($event)" // like mouseMove
        (panend)="onPanEnd($event)" // like mouseUp
      >
      </div>
```

**Comment by pIvan** [comment]
Thanks @StringKe, I'll see what can I do this weekend

**Comment by StringKe** [comment]
maybe you need to modify the mousedown and mouseup of all components in `projects/iplab/ngx-color-picker/src/lib/components/parts`?

**Comment by pIvan** [comment]
Hi @StringKe I have already started with this, 
but I'm trying to test it in detail

**Comment by StringKe** [comment]
Maybe you can add `OnStart` and `OnEnd` events to `projects/iplab/ngx-color-picker/src/lib/helpers/color.class.ts` add corresponding listeners during component init?

**Comment by pIvan** [comment]
Hi @StringKe,

problem is next, chrome picker, same as any other is
composed of several different components, on each different component then we should track
start value and end value. How to define which is the start value of chrome picker if you start to slide
opacity, and then you start to slide hue or saturation?

When to emit start value, and when to emit end value?

How I see it is to add those events on each child component, then you can combine them
to build your component?

Kind regards,
Ivan
