### ISSUE TITLE
Add the support of hexa to chrome-picker component

### ISSUE THREAD

**Issue by LucioBrucio** [pIvan/ngx-color-picker#26]
When using chrome-picker component the indicator sub component can show the current color in rgba, hlsa and hex but not in hexa. In the attached screenshot even if i changed the alpha value, the hex value doesn't change.
![Screenshot 2021-02-25 at 10 19 07](https://user-images.githubusercontent.com/15995466/109131419-15671480-7753-11eb-9ee0-06fc3d1d1689.png)

**Comment by pIvan** [comment]
Hi @LucioBrucio,

I'll add it this week, thanks @LucioBrucio!
