### ISSUE TITLE
Entering hexcode adds characters automatically

### ISSUE THREAD

**Issue by RaminGe** [pIvan/ngx-color-picker#34]
Hey there 👋

We are having an issue with the hex input field. When I enter characters it keeps adding or "completing" the hex code as well as when you hit backspace to remove the numbers. Check this screen recording:

https://user-images.githubusercontent.com/16246664/123105291-fabe5700-d437-11eb-93bd-4eb26e7c2024.mov

The code used:

**Template**
```html
<hex-input-component [(color)]="color"></hex-input-component>
```

**Component**
```javascript
    private _color: Color = new Color('#000000');
    get color() {
        return this._color;
    }
    @Input() set color(newColor: Color) {
        this._color = newColor;
    }
```

We are on version 2.1.0

**Comment by pIvan** [comment]
Hi @RaminGe,
thanks for reporting the problem, it will be fixed this week.

Kind regards,
Ivan

**Comment by pIvan** [comment]
Hi @RaminGe,
self-completing 3-character hexadecimal entry is removed, now it is available at enter press.
Can you confirm if the behavior is ok?
