### ISSUE TITLE
Unable to get an event on click of pre-selected color

### ISSUE THREAD

**Issue by urvil-mehta-tfs** [pIvan/ngx-color-picker#5]
After opening color picker, if i click on selected color, I need an event to close color picker. Can you please point me if there is anything available?

**Comment by pIvan** [comment]
Hi @urvil-mehta-tfs can you give me an example of code how you made that component, so I could give you a best-suited answer?

**Comment by urvil-mehta-tfs** [comment]
Hi plvan, I created a sample for you to see my requirement. In below link, when i click on color, color picker is opened, i should be to close color picker on click of selected color. Also, I should be able to close color picker on clicking anywhere outside.

https://stackblitz.com/edit/angular-vmmemd

Appreciate your help.

**Comment by pIvan** [comment]
Hi @urvil-mehta-tfs,
[here](https://pivan.github.io/ngx-color-picker/#wrap-component) you can find example of how to wrap components to fit your needs (use last version 1.0.5).
