### ISSUE TITLE
ColorPickerControl is not available

### ISSUE THREAD

**Issue by sz274071580** [pIvan/ngx-color-picker#6]
import { ColorPickerControl } from '@iplab/ngx-color-picker/lib/helpers/control.class';
const colorControl = new ColorPickerControl();

When I follow the steps above, I always throw the following error, what should I do? Is my package path reference wrong?

Failed to compile.

./src/app/web/test1.component.ts
Module not found: Error: Can't resolve '@iplab/ngx-color-picker/lib/helpers/control.class' in 'D:\other\angulartest4\src\app\web'

angular:8.1.0
chrome:73.0.3683.103

**Comment by pIvan** [comment]
Hi @sz274071580,
Your import is not correctly written, should be:
**import { ColorPickerControl } from '@iplab/ngx-color-picker';**

Kind regards,
Ivan

**Comment by sz274071580** [comment]
> Hi @sz274071580,
> Your import is not correctly written, should be:
> **import { ColorPickerControl } from '@iplab/ngx-color-picker';**
> 
> Kind regards,
> Ivan

Thank you very much
