### ISSUE TITLE
Compat color picker with horizontal hue bar

### ISSUE THREAD

**Issue by genemars** [pIvan/ngx-color-picker#68]
Using the picker in a Material UI dialog, when sliding the vertical hue bar can sometimes trigger the "pull down to refresh" functionality of the browser even if `overscroll-behavior: contain!important;` is set.
So as a possible solution it would be nice to have an attribute to set the hue bar to horizontal, since there is already such attribute for the stand-alone `hue-component`.

![Screenshot_20230204-210101264](https://user-images.githubusercontent.com/6654265/216787604-cc80fc89-5927-4d12-af75-1de01c9b6449.jpg)

**Comment by pIvan** [comment]
Hi @genemars, I plan to make some changes this week.

**Comment by genemars** [comment]
Looking forward to try next release then =)

**Comment by pIvan** [comment]
Hi @genemars did you tried touch-action property? Will that be better solution for you?

**Comment by genemars** [comment]
Hi @pIvan thanks for the hint, I added this:
```css
compact-picker {
  touch-action: none;
}
```
and it did the trick =)
