### ISSUE TITLE
Hue value not updated for colors with hue = 0

### ISSUE THREAD

**Issue by PierreMassanes** [pIvan/ngx-color-picker#69]
Hi @pIvan,

When calling [setValueFrom](https://github.com/pIvan/ngx-color-picker/blob/be9ff0bbc61a9813d1739d76d59e94758c7a69fe/projects/iplab/ngx-color-picker/src/lib/helpers/control.class.ts#L38) with any color having the hue set to 0, the hue value is not updated.
For example, here I selected a green color through the picker, then called setValueFrom with the color #E60303 which has a hue of 0.
![image](https://user-images.githubusercontent.com/11056871/220283712-ec0db064-8555-41b5-b84a-3b95d17c1445.png)
You can see that the hue was not updated, but the value is the good one.

In setHueColor we have this:
```
    private setHueColor(color: Color) {
        if (this.hueValue && color.getHsva().hue > 0 || !this.hueValue) {
            this.hueValue = new Color().setHsva(color.getHsva().hue);
        }
    }
```

I think that the `color.getHsva().hue > 0` is failing in that case and should be `color.getHsva().hue >= 0`.

What do you think ?

Thanks,
Pierre

**Comment by pIvan** [comment]
Hi @PierreMassanes you're right, fix will be ready tomorrow :)

**Comment by PierreMassanes** [comment]
Thanks a lot @pIvan !

**Comment by pIvan** [comment]
You can try it now and let me know if it's okay, thank you! :)
