### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by MasterBroki** [pIvan/ngx-color-picker#70]
Hi,

is it possible to support angular 15?

Thanks!
npm ERR! While resolving: @iplab/ngx-color-picker@14.2.3
npm ERR! Found: @angular/animations@15.2.6
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^15.2.6" from the root project
npm ERR!   peer @angular/animations@"^14.0.0 || ^15.0.0" from @angular/material@14.2.7   
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^14.2.6" from the root project
npm ERR!     peer @angular/material@"14.2.7" from @angular/material-moment-adapter@14.2.7
npm ERR!     node_modules/@angular/material-moment-adapter
npm ERR!       @angular/material-moment-adapter@"^14.2.6" from the root project
npm ERR!   3 more (@angular/platform-browser, ...)

**Comment by pIvan** [comment]
Hi @MasterBroki, there is a version 15.0.2 which is compatible with Angular >= 15.0.0
