### ISSUE TITLE
Angular 17 - Standalone, NCF, Signals

### ISSUE THREAD

**Issue by Sergiobop** [pIvan/ngx-color-picker#78]
Hi!

First of all, thank you for this package, awesome work.

Do you have plans to upgrade the project to Angular 17? If you do..

- Will you swap to the new control flow?
- Will you use standalone components for the different pickers instead of one module?
- Will you use signals when possible? I think you can simplify the code a lot

I think this lib has the potential to become the best color picker in Angular.

Thanks again

**Comment by pIvan** [comment]
Hi @Sergiobop,

Thank you!

First, I'll start by migrating the project to Angular 17, which will probably mean a new control flow. I've been considering standalone components for some time. However, currently, I'm finalizing some adjustments on color conversions to set RGBA for the base color, and all other colors will be derived from it. Additionally, I might wait a bit longer before using signals, possibly implementing them within the component itself. After that, I may consider redesigning the public part of the API.

**Comment by Sergiobop** [comment]
Hi @pIvan , thank you for your fast response. I agree on the signals change.

Standalone however, would be a great improvement. For example, i just use the chrome picker inside a cdkOverlay component, and i have to import all the components right now with the module.

If you allow me, I would also suggest some improvements in the chrome picker, like a new input to set the selectedPresentation. In my apps, the users are used to the "HEX" colors, and right now it always start on RGBA mode

Thanks!

**Comment by pIvan** [comment]
Thank you, "_selectedPresentation_" will be one of the new features.

**Comment by pIvan** [comment]
Hi @Sergiobop,

a new versions (17.0.0 and 17.1.0) of the library are available, which are compatible with Angular 17. Additionally, all components are standalone, and a new control flow has been implemented. The implementation of signals remains as a new feature. Furthermore, there have been minor adjustments made here to facilitate easier message localization through configuration using the COLOR_PICKER_CONFIG injection token.

**Comment by Sergiobop** [comment]
Wow, that was fast,

Thanks a lot @pIvan

**Comment by pIvan** [comment]
Hi @Sergiobop, thank you for the bug report. I just identified the issue—I made a mistake by leaving providers under the module definition. Consequently, when the component is used separately, there are no providers available.

**Comment by elementalPRESS** [comment]
I ran into the same problem but wasn't able to find a solution yet. Do you have a quick fix to get the ColorPicker make running again?

**Comment by elementalPRESS** [comment]
> > I ran into the same problem but wasn't able to find a solution yet. Do you have a quick fix to get the ColorPicker make running again?
> 
> Hi @elementalPRESS, which version do you use?

I'm using the latest version and Angular 17.0.8

**Comment by pIvan** [comment]
> > > I ran into the same problem but wasn't able to find a solution yet. Do you have a quick fix to get the ColorPicker make running again?
> > 
> > 
> > Hi @elementalPRESS, which version do you use?
> 
> I'm using the latest version and Angular 17.0.8

Can you try 17.1.1 with an example of code a few lines above

**Comment by pIvan** [comment]
I think we misunderstood each other. What version of this library are you using? And is the entire project configured as standalone components, or are there parts that are modules?

Does your application's bootstrap look something like this?

```
bootstrapApplication(
    AppComponent, {
    providers: [
        { provide: COLOR_PICKER_CONFIG, use... } or importProvidersFrom(ColorPickerModule)
    ]
});
```

**Comment by elementalPRESS** [comment]
> I think we misunderstood each other. What version of this library are you using? And is the entire project configured as standalone components, or are there parts that are modules?

Ahhhh :-) It's a module.

> Does your application's bootstrap look something like this?
> 
> ```
> bootstrapApplication(
>     AppComponent, {
>     providers: [
>         { provide: COLOR_PICKER_CONFIG, use... } or importProvidersFrom(ColorPickerModule)
>     ]
> });
> ```

I don't have something like this. I just have it in my module imports and use it very plain without any special configurations:

	@NgModule({
		imports: [CommonModule, FormsModule, ColorPickerModule, ...],
		declarations: [...],
		exports: [...],
	})
	export class TextDesignerModule {}

In the template:

	<sketch-picker class="sketch-picker" [(color)]="color" (colorChange)="changeValue($event)"></sketch-picker>

**Comment by pIvan** [comment]
And what is the exact error you are getting? Can you paste the log and an example component where you are using this template?

**Comment by elementalPRESS** [comment]
> And what is the exact error you are getting? Can you paste the log and an example component where you are using this template?

    NullInjectorError: R3InjectorError(ScoreboardModule)[ColorPickerConfig -> ColorPickerConfig -> ColorPickerConfig -> InjectionToken COLOR_PICKER_CONFIG -> InjectionToken COLOR_PICKER_CONFIG]: 
      NullInjectorError: No provider for InjectionToken COLOR_PICKER_CONFIG!
        at NullInjector.get (core.mjs:5626:27)
        at R3Injector.get (core.mjs:6069:33)
        at R3Injector.get (core.mjs:6069:33)
        at injectInjectorOnly (core.mjs:911:40)
        at Module.ɵɵinject (core.mjs:917:60)
        at Object.ColorPickerConfig_Factory [as factory] (iplab-ngx-color-picker.mjs:820:103)
        at core.mjs:6189:43
        at runInInjectorProfilerContext (core.mjs:867:9)
        at R3Injector.hydrate (core.mjs:6188:17)
        at R3Injector.get (core.mjs:6058:33)
    handleError @ error.interceptor.ts:43
    next @ core.mjs:32328
    next @ Subscriber.js:91
    _next @ Subscriber.js:60
    next @ Subscriber.js:31
    (anonymous) @ Subject.js:34
    errorContext @ errorContext.js:19
    next @ Subject.js:27
    emit @ core.mjs:14310
    (anonymous) @ core.mjs:14749
    invoke @ zone.js:368
    run @ zone.js:129
    runOutsideAngular @ core.mjs:14619
    onHandleError @ core.mjs:14749
    handleError @ zone.js:372
    runGuarded @ zone.js:142
    api.microtaskDrainDone @ zone.js:1054
    drainMicroTaskQueue @ zone.js:588
    invokeTask @ zone.js:487
    invokeTask @ zone.js:1631
    globalCallback @ zone.js:1662
    globalZoneAwareCallback @ zone.js:1695

**Comment by pIvan** [comment]
Did you include the ColorPickerModule module in the ScoreboardModule?

**Comment by elementalPRESS** [comment]
> Did you include the ColorPickerModule module in the ScoreboardModule?

Nope, but in the TextDesignerModule and the TextDesignerModule is imported in the ScoreboardModule. This was working for some years without any issues.

**Comment by pIvan** [comment]
Can you try version 17.1.2?

**Comment by elementalPRESS** [comment]
> Can you try version 17.1.2?

Your fix works like a charm. Thank you very much!

**Comment by pIvan** [comment]
thank You! ;)

**Comment by Sergiobop** [comment]
Hi @pIvan !

I hope everything is going well.

Angular 19 released last week. I think the library is perfectly prepared to work without problems, can we change the package.json to avoid future blocks in updating angular apps?

I'm thinking something like:

```
    "@angular/common": ">=18.0.0",
    "@angular/core": ">=18.0.0",
    "@angular/animations": ">=18.0.0"
```

**Comment by pIvan** [comment]
Hi @Sergiobop, I encountered some problems during the update process, but the package is now compatible with version 19
