### ISSUE TITLE
Problem with the [hideOnClickOutside]="true"

### ISSUE THREAD

**Issue by aleksander351** [pIvan/ngx-color-picker#82]
When you drag the mouse to the edge, (i.e. wanting to select #FFF or #000) and release the mouse by accident outside the color palette, it closes the dialogue. Not sure if this is a bug or a feature or there is a property that prevents that.

See the mouse cursor position when releasing the mouse button.
![image](https://github.com/pIvan/ngx-color-picker/assets/7508670/7c70bdf0-5b5f-45ca-8bd8-16dd3a6f7047)

**Comment by pIvan** [comment]
Hi @aleksander351,

That component is just an example wrapper demonstrating how to set up a color picker as a floating element. It should be easy to register other events on this wrapper component, but this functionality is not part of the library itself.
